#!/bin/bash

export APP_NAME=

if [ "$APP_NAME" = "" ]; then
  echo "APP_NAME must be set."
  exit;
fi

if [ "$DEIS_USERNAME" = "" ]; then
  echo "DEIS_USERNAME must be set."
  exit;
fi

if [ "$DEIS_PASSWORD" = "" ]; then
  echo "DEIS_USERNAME must be set."
  exit;
fi

if [ "$DEIS_PRD_URL" = "" ]; then
  echo "DEIS_PRD_URL must be set."
  exit;
fi

if [ "$DEIS_STG_URL" = "" ]; then
  echo "DEIS_STG_URL must be set."
  exit;
fi

# Eventually logout from a controller
echo "LOGOUT"
deis logout

# Create app in production
echo "[PRD] CREATE"
deis apps:create $APP_NAME --no-remote

# Add git remote in production
echo "[PRD] ADD GIT REMOTE"
git remote add deis-prd ssh://git@deis.$DEIS_PRD_URL:2222/$APP_NAME.git

# Setup env vars in production
echo "[PRD] SET ENV VARS"
echo "Missing implementation... Skip."

# Logout from prd controller
echo "[PRD] LOGOUT"
deis logout

# Login to staging
echo "[STG] LOGIN"
deis auth:login --username=$DEIS_USERNAME --password=$DEIS_PASSWORD deis.$DEIS_STG_URL

# Create app in production
echo "[STG] CREATE"
deis apps:create $APP_NAME --no-remote

# Add git remote in production
echo "[STG] ADD GIT REMOTE"
git remote add deis-prd ssh://git@deis.$DEIS_STG_URL:2222/$APP_NAME.git

# Setup env vars in production
echo "[STG] SET ENV VARS"
echo "Missing implementation... Skip."

# Logout from stg controller
echo "[STG] LOGOUT"
deis logout
