#!/bin/bash

export APP_NAME=

if [ "$APP_NAME" = "" ]; then
  echo "APP_NAME must be set."
  exit;
fi

./login $1

if [ "$1" = "prd" ]; then
  echo "Deploying to production"
  git push deis-prd master
else
  echo "Deploying to staging"
  git push deis-stg development
fi

# Logout
echo "LOGOUT"
deis logout
