#!/bin/bash

if [ "$DEIS_USERNAME" = "" ]; then
  echo "DEIS_USERNAME must be set."
  exit;
fi

if [ "$DEIS_PASSWORD" = "" ]; then
  echo "DEIS_USERNAME must be set."
  exit;
fi

if [ "$1" = "prd" ]; then
  if [ "$DEIS_PRD_URL" = "" ]; then
    echo "DEIS_PRD_URL must be set."
    exit;
  fi

  echo "Logging in to production"
  deis auth:login --username=$DEIS_USERNAME --password=$DEIS_PASSWORD deis.$DEIS_PRD_URL
else
  if [ "$DEIS_STG_URL" = "" ]; then
    echo "DEIS_STG_URL must be set."
    exit;
  fi

  echo "Logging in to staging"
  deis auth:login --username=$DEIS_USERNAME --password=$DEIS_PASSWORD deis.$DEIS_STG_URL
fi
